/*
 * existingApis
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ProductDetail;
import io.swagger.client.model.SimilarProducts;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Gets a product detail
     *
     * Returns the product detail for a given productId
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getProductProductIdTest() throws Exception {
        String productId = null;
        ProductDetail response = api.getProductProductId(productId);

        // TODO: test validations
    }
    /**
     * Gets the ids of the similar products
     *
     * Returns the similar products to a given one ordered by similarity
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getProductSimilaridsTest() throws Exception {
        String productId = null;
        SimilarProducts response = api.getProductSimilarids(productId);

        // TODO: test validations
    }
}
